"""Configuration file for the Sphinx documentation builder."""

import os
import sys

import lost_years

# Add the package path for autodoc
sys.path.insert(0, os.path.abspath("../../"))


# -- Project information -----------------------------------------------------
project = "lost_years"
copyright = "2024, Gaurav Sood, Suriyan Laohaprapanon"
author = "Gaurav Sood, Suriyan Laohaprapanon"

# The version info for the project - import from package
version = lost_years.__version__
release = version


# -- General configuration ---------------------------------------------------
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
    "sphinx.ext.intersphinx",
    "sphinx_autodoc_typehints",
]

templates_path = ["_templates"]
exclude_patterns = []

# The suffix(es) of source filenames
source_suffix = ".rst"

# The root toctree document
root_doc = "index"

# Language for content autogenerated by Sphinx
language = "en"


# -- Options for HTML output -------------------------------------------------
html_theme = "furo"

html_theme_options = {
    "source_repository": "https://github.com/gojiplus/lost_years/",
    "source_branch": "master",
    "source_directory": "docs/source/",
}

html_title = "lost_years"
html_static_path = ["_static"]


# -- Extension configuration -------------------------------------------------

# Intersphinx configuration
intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "pandas": ("https://pandas.pydata.org/docs/", None),
}

# Napoleon settings
napoleon_google_docstring = True
napoleon_numpy_docstring = True
napoleon_include_init_with_doc = False
napoleon_include_private_with_doc = False
napoleon_include_special_with_doc = False
napoleon_use_admonition_for_examples = False
napoleon_use_admonition_for_notes = False
napoleon_use_admonition_for_references = False
napoleon_use_ivar = False
napoleon_use_param = True
napoleon_use_rtype = True

# Autodoc settings
autodoc_default_options = {
    "members": True,
    "member-order": "bysource",
    "special-members": "__init__",
    "undoc-members": True,
    "exclude-members": "__weakref__",
}


# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = "lost_yearsdoc"


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',
    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',
    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',
    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (
        root_doc,
        "lost_years.tex",
        "lost_years Documentation",
        "Gaurav Sood, Suriyan Laohaprapanon",
        "manual",
    ),
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [(root_doc, "lost_years", "lost_years Documentation", [author], 1)]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        root_doc,
        "lost_years",
        "lost_years Documentation",
        author,
        "lost_years",
        "Get Expected Number of Years Lost",
        "Miscellaneous",
    ),
]
